### ISSUE TITLE
Migrate to hooks to reduce size

### ISSUE THREAD

**Issue by saitonakamura** [researchgate/react-intersection-observer#130]
I took at the source code and found several places where usage of hooks would help reduce size (though I gotta say, 1.7 kb is still impressive) and maybe simplify the code (reactive props via dependencies, for instance). I would take a shot at it, but there's a problem with backwards compatibility: hooks are 16.8+, and current peer deps are 16.3+

I'd like to hear your thoughts on that, maybe new major version is an option

**Comment by Rendez** [comment]
There's a breaking change I would like to introduce to remove `findDOMNode`. It involves passing our ref callback to `this.props.children`. That would require all usages to be changed to forward the ref prop to the respective DOM element yourself.

If we create a separate implementation next to the current one just for hooks, we can then have users opt-in to hooks, for example:
```js
const { useState } from 'react';
const { useIntersectionObserver } from '@rg/react-intersection-observer';

const Foo = () => {
  const [intersecting, setIntersecting] = setState(false);
  const callback = ({ isIntersecting }) => {
    setIntersecting(isIntersecting);
  }
  const {ref} = useIntersectionObserver(callback, options);
  return <Bar><div ref={ref}>{intersecting}</div></Bar>;
}
```
The peerDependency is less of a worry to me, since we coulddocument the fact that using hooks requires 16.8+.

Do you want to take a shot?

**Comment by saitonakamura** [comment]
That sound like a good idea, thanks! Yeah, this week probably
