### ISSUE TITLE
Enhancement: Does this actually not work with React v15?

### ISSUE THREAD

**Issue by sgpinkus** [researchgate/react-intersection-observer#158]
Current package.json:

```
  "peerDependencies": {
    "react": "^16.3.2",
    "react-dom": "^16.3.2"
  },
```

I'm not sure, but seems to work fine with React v15. What specifically is required from React v16? If nothing, could I please make a "suggested enhancement":

```
  "peerDependencies": {
    "react": ">=15",
    "react-dom": ">=15"
  },
```

If it does require v16, it would be great if you could add a quick note in the README about why.

**Comment by Rendez** [comment]
On the surface it works well, but if the observing node changes you'll run into a bug: https://github.com/researchgate/react-intersection-observer/blob/master/src/IntersectionObserver.ts#L109. That's one of the a reasons why React 15 is no longer supported, because it made logic like this extremely and unnecessarily complex.
