### ISSUE TITLE
Rm "module": "lib/es/src/index.js", from package.json

### ISSUE THREAD

**Issue by sgpinkus** [researchgate/react-intersection-observer#159]
## Expected behavior
Our webpack build shouldn't fail :).

## Current behavior
For some reason I don't completely understand, our webpack build is failing because of this line in package.json:

```
  "module": "lib/es/src/index.js",
```

I don't even know what the `module` field in package.json does (newb ..). But it seems to be causing ES6 Javascript to leak into our built web code. Is it needed to package es code?

## Steps to reproduce
Can only provide steps to not reproduce: rm line:

```
  "module": "lib/es/src/index.js",
```

## Context (environment)
Node: v12.18.1
react-intersection-observer: v1.3.3
webpack: v3.

**Comment by danez** [comment]
The `module` field is similar to the `main` field and specifies the entrypoint, but with the difference that the source located there contains ES-Modules (import/export) and not commonjs (`require()`) code. So we are definitely not going to remove it, because for example webpack uses it, so it can better optimize the bundles (via tree shaking and module concatenation).

But I'm curious what the error is you get from webpack. Can you post the error message? Without it there is no way we can help.

**Comment by sgpinkus** [comment]
> The module field is similar to the main field and specifies the entrypoint

OK. My understanding of this has gotten slightly  better over the last day or so. Can see others are including /es/ and `modules` field in builds too.  Thanks for explanation.

> But I'm curious what the error is you get from webpack. Can you post the error message? Without it there is no way we can help.

Absolutely. Well it's not from webpack exactly. It's from Uglify that runs over the webpack output. The particular error is:

> ERROR in server.js from UglifyJs
Unexpected token: operator (>) [server.js:9373,59]

I traced this down to an arrow function left inside the `parseRootMargin`  function of this package. If I remove `module` from package.json or downgrade to 1.1.3 this error goes away and the build succeeds.

**Comment by danez** [comment]
Can you try with version 1.3.4? It should now work correctly.

**Comment by sgpinkus** [comment]
Yes it works now. Thanks!
