### ISSUE TITLE
isIntersecting returns true when element is outside of viewport

### ISSUE THREAD

**Issue by klase** [researchgate/react-intersection-observer#24]
## Expected behavior
isIntersecting should return false when element is scrolled outside of viewport (with set threshold).

## Current behavior
onChange triggers when element is scrolled out of viewport but returns true instead of false. This only seem to happen when threshold is set. When removing the threshold property everything works as expected.

## Steps to reproduce
https://codesandbox.io/s/6z00y2vjwr

**Comment by Rendez** [comment]
I believe that's expected behavior if you set the threshold only to 1. If you modify to [0, 1] instead you should get the expected result.

**Comment by klase** [comment]
Setting [0, 1] gives me the same behaviour as not setting threshold at all (Chrome 62.0.3202.94) . Shouldn't setting it to 1 give isIntersecting: true only when the whole element is in the viewport, and false when any part of it is outside the viewport?

**Comment by Rendez** [comment]
Indeed it should switch back to false after the threshold step. Here's the same codesandbox exhibiting the same behavior in Chrome with the native API: 
https://codesandbox.io/s/py9wmyy297

This proves that the behavior is native and has nothing to do with this repo. I think I have an idea of what's going on...

If you scroll back up very aggressively you'll get the value to switch to `false` sometimes, because of the async nature of this API. This indicates to me that Chrome treats intersections as inclusive, so it could be a case of [edge-adjacent intersections](https://github.com/w3c/IntersectionObserver/issues/222#issuecomment-311827053). I guess we should [open an issue](https://github.com/w3c/IntersectionObserver/issues) in the w3c polyfill repo about this, in order to clarify the behavior.

**Comment by klase** [comment]
According to this https://bugs.chromium.org/p/chromium/issues/detail?id=713819 it's expected behaviour so perhaps isIntersecting can't be used in this way. I guess checking intersectionRatio in combination with [0, 1] as targets would work but event.interSectionRatio in the callback doesn't give the exact value of the target intersectionRatio so only works in simple use cases (i.e checking less than or greater than).

**Comment by klase** [comment]
Feel free to close this btw as it's a native issue.

**Comment by Rendez** [comment]
Thanks for pasting the link, I wasn't fully aware of the purpose of `isIntersecting` so I'll make sure to document the usages better. Cheers!
