### ISSUE TITLE
Use of for...of is forcing use of Symbol polyfill

### ISSUE THREAD

**Issue by heygrady** [researchgate/react-intersection-observer#36]
https://github.com/researchgate/react-intersection-observer/blob/e2e566cdadbcae6e12fddb8146587ad9f91af585/src/IntersectionObserverContainer.js#L10

https://github.com/researchgate/react-intersection-observer/blob/e2e566cdadbcae6e12fddb8146587ad9f91af585/src/IntersectionObserverContainer.js#L39

Although `Symbol` is not used directly by this package, the use of `for...of` is forcing anyone using it to add the [Symbol polyfill](https://github.com/zloirock/core-js/blob/master/modules/es6.symbol.js) to their project (if they want to support IE11). This isn't the end of the world but in my case it's adding a few KB to my polyfill bundle.

I understand that `for...of` is more convenient than the equivalent `for (let i = 0; i < array.length; i++)` loop we'd need instead. However, a relatively small change in this library would mean that consumers that don't otherwise need `Symbol` won't need to add a sizable polyfill to their project.

The other [primitive requirements](https://github.com/researchgate/react-intersection-observer#notes) for `Map` and `Set` align with the [environment recommendations for React](https://reactjs.org/docs/javascript-environment-requirements.html). 

related to https://github.com/researchgate/react-intersection-observer/issues/16

**Comment by Rendez** [comment]
You're basically right about having to add `Symbol` support. The reason I chose `for .. of` is because it allows us to do an early return in both cases. This is specially important for the second link where we loop over the targets, as the same instance could potentially be observing thousands of elements. However, this is easily solvable by converting Set into Array.

For the first case – the one where we iterate over the Map intance – we could make use of `.forEach` instead which would not require `Symbol`, but that means we must iterate over all instances, save the found one and then return it. This can be optimized so that the work inside the callback bails out if the match is found. I doubt anyone creates thousands of observer instances, there aren't that many options to even do that :)

Do you feel like opening your first PR on this repo?
