### ISSUE TITLE
Need entry and exit hooks

### ISSUE THREAD

**Issue by vibhor-j** [researchgate/react-intersection-observer#56]
Description
We need entry and exit hooks, so that we can easily add callbacks for entry or exit of the target element

Example
We want to have an entry event when the target element appears on view port and an exit event when it leaves view port.
As the library support array of threshold values, we can find the min value from that threshold and check if target element's intersection ratio is greater than or less than min threshold value. 

Why this feature would be useful to this project
End user can simply use entry and exit hooks if he wants to do something on entry or exit of target element. Entry and Exit callbacks can be non mandatory to make it backward compatible.

**Comment by vibhor-j** [comment]
I have raised this PR for this change
https://github.com/researchgate/react-intersection-observer/pull/57

**Comment by Rendez** [comment]
Hi @vibhor-j and thanks for taking the time to suggest a new feature and even do all the work of opening a PR. While I see the value of this feature, it isn't something I'd like to include in the library itself.
The reason is, since the beginning we've tried to keep react-intersection-observer very small and close to the native JS API, so that anyone would use it as a building foundation of another component and/or library, instead of adding extra things to the core of it.

Looking at the proposed changes in #57, I believe it would be very easy to create your own component on top of this one by passing a handler to `onChange` and doing your `onExit`/`onEnter` logic there to accomplish the same thing. Unless there's a very specific reason why this logic should live in react-intersection-observer, I prefer to keep it unopinionated about how to handle events, and leave that to the implementor, outside of the scope.
