### ISSUE TITLE
Doesn't work as expected. All Change events fire upon start. Never again even after scroll

### ISSUE THREAD

**Issue by ronenmagid** [researchgate/react-intersection-observer#82]
## Expected behavior
OnChange fired dynamically when elements go in and out of viewport.

## Current behavior
OnChange is fired immediately for ALL components, the intersect property of the event is correct, but those who get `false` never have an event when I scroll them into the viewport. No events are ever fired for any components after the initial firing of the event for ALL components, intersecting or not. 

## Steps to reproduce
```
<Observer onChange={this.onIntersectionChange}>
   <Content>
       {text}
    <Content>
</Observer>
```

```
 onIntersectionChange = (event, unobserve) => {
        if (event.isIntersecting) {
           // unobserve();
        }
        console.log("in view port: " + event.isIntersecting );
    };
```

## Context (environment)
React 16.12.0
Chrome (latet)

**Comment by okovpashko** [comment]
@ronenmagid this is an expected behavior to get `onChange` called on the observer initialization.
That's how `IntersectionObserver` [works by design](https://developer.mozilla.org/en-US/docs/Web/API/Intersection_Observer_API#Targeting_an_element_to_be_observed).

Have you looked at the [examples](https://developer.mozilla.org/en-US/docs/Web/API/Intersection_Observer_API#Targeting_an_element_to_be_observed)? They might be extremely useful when trying to deal with `IntersectionObserver` and with this library for the first time.

**Comment by Rendez** [comment]
Thanks @okovpashko
